name = "Optifinefabric"
author = "namenlosxy"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "435a639eaed4c381a45276bd3331604aac12415ec721f930623be07b85540f80"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
