name = "Optifinefabric"
author = "namenlosxy"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c66c3ec89f4be240a7082587606e09dcff914f1277b923c5ed3811cb7733000"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17.1"]
