name = "Optifinefabric"
author = "namenlosxy"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afce78838ec8ea9490947f3e1685b67b911bce52df26d74757d9a514e42c2289"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
