name = "Optifinefabric"
author = "namenlosxy"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "495f7f2c0ae9bd42ad1a7fb845510e22f09edb1e1420ee5be531a319a8534be7"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
