name = "Optifinefabric"
author = "namenlosxy"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a46589ebb8552a3e82219c2456636e5868d9707a2aa4dedfbf21792a22af420d"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
