name = "Optifinefabric"
author = "namenlosxy"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb16ed5cd6ff1446e9c825f2a8711d930246e64aebd5c8138731a40cc82150e7"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
