name = "Optifinefabric"
author = "namenlosxy"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3661776945f8deaa7049ebee1bdf28848eda39cb4d3ecf24e3f6e733a0dd1de"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17.1"]
