name = "Optifinefabric"
author = "namenlosxy"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84618a07a64015d6c068829672cee75d6535a8e5472e6e8e8d7ab631dc65def3"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
