name = "Custom Splash Screen"
filename = "customsplashscreen-1.1.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/BwFQLeCh/versions/1.1.0/customsplashscreen-1.1.0.jar"
hash-format = "sha512"
hash = "4ef027b9586a8eb00868ddcefe45d0902452018bb1619f814ee8a51081df31522307b1abac4d18fdb94fef7773c5e846c4b29e58793d950f47b27b059fa19b29"

[update]
[update.modrinth]
mod-id = "BwFQLeCh"
version = "3Cv3vvUj"
